version: '3.8'

services:
  # Next.js frontend and API routes
  nextjs:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - FASTAPI_BASE_URL=http://fastapi-gateway:8000
    depends_on:
      - neo4j
      - qdrant
      - fastapi-gateway
    networks:
      - course-navigator

  # FastAPI gateway for RAG + Graph queries
  fastapi-gateway:
    build:
      context: python/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./python:/app
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=password
      - QDRANT_URL=http://qdrant:6333
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - neo4j
      - qdrant
    networks:
      - course-navigator

  # Neo4j graph database
  neo4j:
    image: neo4j:5.15-community
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - ./data/neo4j:/var/lib/neo4j/import/course_data
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*
    networks:
      - course-navigator

  # Qdrant vector database
  qdrant:
    image: qdrant/qdrant:v1.7.3
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage
    networks:
      - course-navigator

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  qdrant_storage:

networks:
  course-navigator:
    driver: bridge