global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # CourseNavigator API metrics
  - job_name: 'coursenavigator-api'
    static_configs:
      - targets: ['host.docker.internal:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    
  # Demo-specific namespace for isolated monitoring
  - job_name: 'demo'
    static_configs:
      - targets: ['host.docker.internal:8000']
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 3s
    # Only scrape during demo runs
    params:
      demo_mode: ['true']

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # System metrics (optional)
  - job_name: 'node'
    static_configs:
      - targets: ['host.docker.internal:9100']
    # Only if node_exporter is running